# -*- coding: utf-8 -*-
"""myfun.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ReKmN4DG6yb_3Us5u-e_5dgClzEf3cui
"""

def add(a, b):
    return a + b

def sub(a, b):
    return a - b

def div(a, b):
    return a / b

def mul(a, b):
    return a * b