# -*- coding: utf-8 -*-
"""runfun.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1frhHd3S8vfSfXRP2-XMSHHGTdAe9dZWd
"""

import sys
import csv

def openfile(fname):
  f = open(fname, "r")
  data = list(csv.reader(f))
  f.close()

  return data
if __name__ == "__main_":
  rdf = openfile("/content/drive/MyDrive/multi/0310/관광정보.csv")
  cnt = 0
  for line in rdf:
    cnt += 1
    print(line)
    if cnt == 10:
      break

